export default{
    SET_ORDER_PAYMENT_METHOD: 'SET_ORDER_PAYMENT_METHOD',
    ADD_PLAYER: 'ADD_PLAYER',
    REMOVE_PLAYER: 'REMOVE_PLAYER',
    REMOVE_LAST: 'REMOVE_LAST',
    REMOVE_DELAY: 'REMOVE_DELAY',
 
}