// NOTE: DO NOT EDIT THIS FILE!!
// Use the constants defined in this file to create your reducer(s) and action creators

export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const TOGGLE_PLAYER_STATUS = 'TOGGLE_PLAYER_STATUS';
